# Generated by Django 2.0.2 on 2018-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'talent_position_type',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='talentpositiontype',
            unique_together={('name', 'id')},
        ),
    ]
