# Generated by Django 2.0.5 on 2019-02-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('talent', 'Talent'), ('client', 'Client'), ('agency', 'Agency')], max_length=10),
        ),
    ]
