# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180710_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('t', 'talent'), ('c', 'client')], max_length=10),
        ),
    ]
