# Generated by Django 2.0.5 on 2019-01-01 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_email', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_team_members', to='team.Team')),
            ],
            options={
                'db_table': 'team_member',
                'ordering': ('id', 'team', 'member_email', 'created'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member_email')},
        ),
    ]
