# Generated by Django 2.0.5 on 2018-11-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_rating_by_client', to='client.Client')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_rating', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_rating',
                'ordering': ('talent', 'updated', 'client'),
                'managed': True,
            },
        ),
    ]
