# Generated by Django 2.0.5 on 2018-11-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentrating',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_ratings_by_client', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='talentrating',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_ratings', to='talent.Talent'),
        ),
    ]
