# Generated by Django 2.0.5 on 2018-12-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_rating', '0002_auto_20181111_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentrating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
