# Generated by Django 2.0.5 on 2018-12-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting_request_talent', '0005_auto_20181221_0240'),
        ('talent_rating', '0003_auto_20181228_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentrating',
            name='casting_request_talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_rating_casting_request_talent', to='casting_request_talent.CastingRequestTalent'),
        ),
    ]
