# Generated by Django 2.0.5 on 2018-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpicture',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
