# Generated by Django 2.0.5 on 2018-11-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_picture', '0002_talentpicture_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentpicture',
            options={'managed': True, 'ordering': ('talent', 'priority', 'caption', 'updated', 'name')},
        ),
    ]
