# Generated by Django 2.0.5 on 2019-02-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_picture', '0004_auto_20181129_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpicture',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentpicture',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talentpicture',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
