# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='skill.Skill')),
            ],
            options={
                'db_table': 'sub_skill',
                'ordering': ('skill', 'name'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='subskill',
            unique_together={('name', 'id')},
        ),
    ]
