# Generated by Django 2.0.5 on 2018-11-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0004_auto_20181129_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subskill',
            old_name='video_steps',
            new_name='video_counts',
        ),
        migrations.AddField(
            model_name='subskill',
            name='have_step2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subskill',
            name='helpful_hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subskill',
            name='introduction_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='subskill',
            name='introduction_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subskill',
            name='opts_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step1_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step1_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step2_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step2_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subskill',
            name='video_audition_type',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
