# Generated by Django 2.0.5 on 2018-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0007_auto_20181201_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='step1_button_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step1_sub_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step2_button_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subskill',
            name='step2_sub_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
