# Generated by Django 2.0.5 on 2018-12-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0008_auto_20181202_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='instruction_button_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subskill',
            name='instruction_button_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subskill',
            name='video_audition_sub_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subskill',
            name='video_audition_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
