# Generated by Django 2.0.5 on 2018-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0009_auto_20181202_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subskill',
            name='instruction_button_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='video_audition_button_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='video_audition_sub_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='video_audition_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
