# Generated by Django 2.0.5 on 2018-12-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0012_subskill_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='formTitle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
