# Generated by Django 2.0.5 on 2018-12-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0013_subskill_formtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subskill',
            old_name='formTitle',
            new_name='form_title',
        ),
    ]
