# Generated by Django 2.0.5 on 2018-12-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0015_remove_subskill_download_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='select_option_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
