# Generated by Django 2.0.5 on 2019-01-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_skill', '0016_subskill_select_option_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='video_audition_view_content_type',
            field=models.CharField(blank=True, choices=[('Nothing Content', 'Nothing Content'), ('Site Content', 'Site Content'), ('Talent Content', 'Talent Content'), ('Reference', 'Reference')], default='Nothing Content', max_length=50),
        ),
    ]
