# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_skills', to='skill.Skill')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_skills', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_skill',
                'ordering': ('talent', 'skill'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='talentskill',
            unique_together={('talent', 'skill')},
        ),
    ]
