# Generated by Django 2.0.5 on 2018-12-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_type', '0005_auto_20181201_0034'),
        ('wizard_question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionWizardQuestionScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=100)),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_type_wizard_question_scenario', to='position_type.PositionType')),
                ('wizard_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_questions_scenario', to='wizard_question.WizardQuestion')),
            ],
            options={
                'db_table': 'wizard_question_scenario',
                'ordering': ('position_type', 'priority'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='positionwizardquestionscenario',
            unique_together={('id',)},
        ),
    ]
