# Generated by Django 2.0.5 on 2018-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position_wizard_question_scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='positionwizardquestionscenario',
            table='position_wizard_question_scenario',
        ),
    ]
