# Generated by Django 2.0.5 on 2018-12-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position_wizard_question_scenario', '0002_auto_20181204_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionwizardquestionscenario',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_type_wizard_question_scenarios', to='position_type.PositionType'),
        ),
        migrations.AlterField(
            model_name='positionwizardquestionscenario',
            name='wizard_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_question_scenarios', to='wizard_question.WizardQuestion'),
        ),
    ]
