# Generated by Django 2.0.5 on 2018-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_wizard_question_scenario', '0003_auto_20181204_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionwizardquestionscenario',
            name='skip_step',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
