# Generated by Django 2.0.5 on 2018-12-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position_wizard_question_scenario', '0004_positionwizardquestionscenario_skip_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionwizardquestionscenario',
            old_name='skip_step',
            new_name='skippable_step',
        ),
    ]
