# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_sub_type', '0001_initial'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPositionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_position_sub_types', to='position_sub_type.PositionSubType')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_position_sub_types', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_position_sub_type',
                'ordering': ('talent', 'position_sub_type'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='talentpositionsubtype',
            unique_together={('talent', 'position_sub_type')},
        ),
    ]
