# Generated by Django 2.0.2 on 2018-07-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent_position_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPositionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('talent_position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_position_sub_types', to='talent_position_type.TalentPositionType')),
            ],
            options={
                'db_table': 'talent_position_sub_type',
                'ordering': ('talent_position_type', 'name'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='talentpositionsubtype',
            unique_together={('name', 'id')},
        ),
    ]
