# Generated by Django 2.0.5 on 2018-12-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ship_name', models.CharField(default='', max_length=100)),
                ('employment_start_date', models.DateTimeField()),
                ('employment_end_date', models.DateTimeField()),
                ('talent_join_date', models.DateTimeField()),
                ('rehearsal_start_date', models.DateTimeField()),
                ('rehearsal_end_date', models.DateTimeField()),
                ('performance_start_date', models.DateTimeField()),
                ('performance_end_date', models.DateTimeField()),
                ('visa_requirements', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Requested', 'Requested'), ('Reviewing', 'Reviewing'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Draft', max_length=10)),
                ('saved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_requests', to='client.Client')),
            ],
            options={
                'db_table': 'casting_request',
                'ordering': ('id', 'client', 'created'),
                'managed': True,
            },
        ),
    ]
