# Generated by Django 2.0.5 on 2018-12-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingrequest',
            name='status_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
