# Generated by Django 2.0.5 on 2019-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_request', '0003_auto_20181228_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Requested', 'Requested'), ('Reviewing', 'Reviewing'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Draft', max_length=20),
        ),
    ]
