# Generated by Django 2.0.5 on 2018-11-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('client_casting_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcastingrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='clientcastingrequest',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.Client'),
            preserve_default=False,
        ),
    ]
