# Generated by Django 2.0.5 on 2018-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_casting_request', '0002_auto_20181109_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='employment_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='employment_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='performance_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='performance_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='rehearsal_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='rehearsal_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientcastingrequest',
            name='talent_join_date',
            field=models.DateTimeField(),
        ),
    ]
