# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('multi_selection', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'position_type',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='positiontype',
            unique_together={('name', 'id')},
        ),
    ]
