# Generated by Django 2.0.5 on 2018-11-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontype',
            name='question',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
