# Generated by Django 2.0.5 on 2018-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_type', '0002_positiontype_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiontype',
            options={'managed': True, 'ordering': ('priority', 'name')},
        ),
        migrations.AddField(
            model_name='positiontype',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
