# Generated by Django 2.0.5 on 2018-11-28 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentavailability',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
