# Generated by Django 2.0.5 on 2018-11-28 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talent_availability', '0003_auto_20181128_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentavailability',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
