# Generated by Django 2.0.5 on 2018-12-17 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talent_availability', '0004_auto_20181128_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentavailability',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='talentavailability',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
