# Generated by Django 2.0.5 on 2018-12-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_availability', '0005_auto_20181217_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentavailability',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentavailability',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
