# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_interview_prep_countdown', models.IntegerField(default=30)),
                ('video_interview_response_time', models.IntegerField(default=120)),
            ],
        ),
    ]
