# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent_position_type', '0001_initial'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentAdditionalPositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_additional_position_types', to='talent.Talent')),
                ('talent_position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_additional_position_types', to='talent_position_type.TalentPositionType')),
            ],
            options={
                'db_table': 'talent_additional_position_type',
                'managed': True,
            },
        ),
    ]
