# Generated by Django 2.0.5 on 2018-12-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wizard_question', '0001_initial'),
        ('sub_skill', '0015_remove_subskill_download_video_link'),
        ('position_sub_type', '0004_auto_20181201_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=100)),
                ('is_sub_skill', models.BooleanField(default=False)),
                ('position_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_sub_type_wizard_question_answers', to='position_sub_type.PositionSubType')),
                ('sub_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_skill_wizard_question_answers', to='sub_skill.SubSkill')),
                ('wizard_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_question_answers', to='wizard_question.WizardQuestion')),
            ],
            options={
                'db_table': 'wizard_question_answer',
                'ordering': ('priority',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='wizardquestionanswer',
            unique_together={('id',)},
        ),
    ]
