# Generated by Django 2.0.5 on 2018-12-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_question_answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizardquestionanswer',
            options={'managed': True, 'ordering': ('wizard_question', 'priority')},
        ),
    ]
