# Generated by Django 2.0.5 on 2018-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_question_answer', '0003_wizardquestionanswer_is_skippable'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardquestionanswer',
            name='not_add',
            field=models.BooleanField(default=False),
        ),
    ]
