# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_sub_types', to='position_type.PositionType')),
            ],
            options={
                'db_table': 'position_sub_type',
                'ordering': ('position_type', 'name'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='positionsubtype',
            unique_together={('name', 'id')},
        ),
    ]
