# Generated by Django 2.0.5 on 2018-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_sub_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionsubtype',
            options={'managed': True, 'ordering': ('position_type', 'priority', 'name')},
        ),
        migrations.AddField(
            model_name='positionsubtype',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
