# Generated by Django 2.0.5 on 2018-11-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_sub_type', '0002_auto_20181127_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionsubtype',
            name='priority',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
