# Generated by Django 2.0.2 on 2018-10-01 05:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Male', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('mailing_addresse1', models.CharField(blank=True, max_length=100)),
                ('mailing_addresse2', models.CharField(blank=True, max_length=100)),
                ('mailing_addresse3', models.CharField(blank=True, max_length=100)),
                ('mailing_addresse4', models.CharField(blank=True, max_length=100)),
                ('mailing_addresse5', models.CharField(blank=True, max_length=100)),
                ('mailing_addresse6', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, default=datetime.date.today)),
                ('emergency_first_name', models.CharField(blank=True, max_length=50)),
                ('emergency_last_name', models.CharField(blank=True, max_length=50)),
                ('emergency_email', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('citizenship', models.CharField(blank=True, max_length=50)),
                ('passport_expiration_date', models.DateField(blank=True, default=datetime.date.today)),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('country_of_current_residence', models.CharField(blank=True, max_length=50)),
                ('have_green_card', models.BooleanField(default=False)),
                ('green_card_expiration_date', models.DateField(blank=True, default=datetime.date.today)),
                ('visa_type', models.CharField(blank=True, max_length=50)),
                ('expiration_date', models.DateField(blank=True, default=datetime.date.today)),
                ('height', models.IntegerField(blank=True, default=0)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('bmi', models.FloatField(blank=True, default=0.0)),
                ('age_range', models.CharField(blank=True, default='', max_length=100)),
                ('head_line', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('worked_cruise_ship', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'talent',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='talent',
            unique_together={('user', 'id')},
        ),
    ]
