# Generated by Django 2.0.2 on 2018-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='bio',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
