# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='bmi',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
