# Generated by Django 2.0.5 on 2018-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='tid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
