# Generated by Django 2.0.2 on 2018-07-24 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20180724_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='talent',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='talent',
            name='passport_expiration_data',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
