# Generated by Django 2.0.2 on 2018-07-26 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0003_auto_20180724_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='talent_position_sub_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='talents', to=settings.AUTH_USER_MODEL),
        ),
    ]
