# Generated by Django 2.0.5 on 2019-02-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_remove_talent_abbreviated_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='locked_dance_combination',
            field=models.BooleanField(default=False),
        ),
    ]
