# Generated by Django 2.0.2 on 2018-08-10 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20180726_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='talent',
            name='green_card_expiration_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='talent',
            name='have_green_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talent',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='talent',
            name='visa_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
