# Generated by Django 2.0.2 on 2018-08-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_auto_20180810_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='passport_expiration_data',
        ),
    ]
