# Generated by Django 2.0.2 on 2018-08-10 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_remove_talent_passport_expiration_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='country_of_current_residence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='talent',
            name='passport_expiration_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
