# Generated by Django 2.0.2 on 2018-08-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_auto_20180810_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='mailing_addresse5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='mailing_addresse6',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
