# Generated by Django 2.0.5 on 2018-12-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0002_talent_tid'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_call_backs', to='client.Client')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_call_backs', to='talent.Talent')),
            ],
            options={
                'db_table': 'call_back',
                'ordering': ('id', 'client', 'talent', 'created'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='callback',
            unique_together={('client', 'talent')},
        ),
    ]
