# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_talent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='birthday',
            field=models.DateTimeField(blank=True),
        ),
    ]
