# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20180716_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='passport_expiration_data',
            field=models.DateField(blank=True),
        ),
    ]
