# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('fluency', models.CharField(choices=[('Fluent', 'Fluent'), ('Conversational', 'Conversational'), ('Basic', 'Basic')], default='Basic', max_length=30)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_languages', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_language',
                'ordering': ('talent', 'language', 'fluency'),
                'managed': True,
            },
        ),
    ]
