# Generated by Django 2.0.2 on 2018-08-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentlanguage',
            name='fluency',
            field=models.CharField(choices=[('Fluent', 'Fluent'), ('Conversational', 'Conversational'), ('Basic', 'Basic')], default='Basic', max_length=10),
        ),
    ]
