# Generated by Django 2.0.2 on 2018-08-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_language', '0002_auto_20180821_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentlanguage',
            name='fluency',
            field=models.CharField(choices=[('Fluent', 'Fluent'), ('Conversational', 'Conversational'), ('Basic', 'Basic')], default='Basic', max_length=30),
        ),
    ]
