# Generated by Django 2.0.2 on 2018-10-16 07:36

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('sex', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=50)),
                ('role', models.CharField(default='', max_length=30)),
                ('role_description', models.CharField(default='', max_length=100)),
                ('able_in', models.DateField(default=datetime.date.today)),
                ('able_out', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('lang', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=30), blank=True, size=None)),
                ('avg_rating', models.CharField(default='', max_length=10)),
                ('comment', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
