# Generated by Django 2.0.2 on 2018-10-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='type',
        ),
        migrations.AddField(
            model_name='talent',
            name='master_type',
            field=models.IntegerField(choices=[(0, 'Vocalist'), (1, 'Dancer'), (2, 'Actor'), (3, 'Aerialist'), (4, 'Musician'), (5, 'Cruise Staff'), (6, 'Youth Staff'), (7, 'Technician')], default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='sub_type',
            field=models.IntegerField(choices=[(0, 'Soprano'), (1, 'Tenor'), (2, 'Alto'), (3, 'Baritone'), (4, 'Jazz'), (1, 'Tap'), (1, 'Ballet'), (1, 'Contemp'), (1, 'Hip-Hop'), (1, 'Lyrical'), (1, 'Ballroom'), (1, 'Gymnastics'), (1, 'Solo'), (1, 'Duo'), (1, 'Trio'), (1, 'Quartet'), (1, 'Band'), (1, 'Audio'), (1, 'Lighting'), (1, 'Video')], default=0),
        ),
    ]
