# Generated by Django 2.0.2 on 2018-10-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181016_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='role',
        ),
        migrations.AddField(
            model_name='talent',
            name='lang1',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Spanish'), (2, 'Portuguese'), (3, 'German'), (4, 'French'), (5, 'Italian'), (6, 'Japanese'), (7, 'Mandarin'), (8, 'Cantonese')], default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='lang2',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Spanish'), (2, 'Portuguese'), (3, 'German'), (4, 'French'), (5, 'Italian'), (6, 'Japanese'), (7, 'Mandarin'), (8, 'Cantonese')], default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='lang3',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Spanish'), (2, 'Portuguese'), (3, 'German'), (4, 'French'), (5, 'Italian'), (6, 'Japanese'), (7, 'Mandarin'), (8, 'Cantonese')], default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='master_role',
            field=models.IntegerField(choices=[(0, 'Sings'), (1, 'Dances'), (2, 'Moves'), (3, 'Acts'), (4, 'Plays')], default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='sub_role',
            field=models.IntegerField(choices=[(0, 'Jazz'), (0, 'Tap'), (0, 'Ballet'), (0, 'Contemp'), (0, 'Hip-Hop'), (0, 'Lyrical'), (0, 'Ballroom'), (0, 'Gymnastics'), (0, 'Piano'), (0, 'Bass'), (0, 'Drums'), (0, 'Strings'), (0, 'Winds'), (0, 'Brass'), (0, 'Percussion')], default=0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
