# Generated by Django 2.0.2 on 2018-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20181016_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='talent_id',
        ),
        migrations.AlterField(
            model_name='talent',
            name='sub_role',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'Jazz'), (2, 'Tap'), (3, 'Ballet'), (4, 'Contemp'), (5, 'Hip-Hop'), (6, 'Lyrical'), (7, 'Ballroom'), (8, 'Gymnastics'), (9, 'Piano'), (10, 'Bass'), (11, 'Drums'), (12, 'Strings'), (13, 'Winds'), (14, 'Brass'), (15, 'Percussion')], default=0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='sub_type',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'Soprano'), (2, 'Tenor'), (3, 'Alto'), (4, 'Baritone'), (5, 'Jazz'), (6, 'Tap'), (7, 'Ballet'), (8, 'Contemp'), (9, 'Hip-Hop'), (10, 'Lyrical'), (11, 'Ballroom'), (12, 'Gymnastics'), (13, 'Solo'), (14, 'Duo'), (15, 'Trio'), (16, 'Quartet'), (17, 'Band'), (18, 'Audio'), (19, 'Lighting'), (20, 'Video')], default=0),
        ),
    ]
