# Generated by Django 2.0.2 on 2018-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20181016_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='vda_number',
            field=models.IntegerField(default=0),
        ),
    ]
