# Generated by Django 2.0.5 on 2018-11-05 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_talent_vda_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('venue', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('status', models.IntegerField(choices=[(0, 'Not Yet Submitted'), (1, 'Requested'), (2, 'In Progress'), (3, 'Completed')], default=0)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('request_name', models.CharField(default='', max_length=100)),
                ('ship_name', models.CharField(default='', max_length=100)),
                ('employStartDate', models.DateField(default=datetime.date.today)),
                ('employEndDate', models.DateField(default=datetime.date.today)),
                ('joinDate', models.DateField(default=datetime.date.today)),
                ('rehearsalPlace', models.CharField(default='', max_length=50)),
                ('rehearsalStartDate', models.DateField(default=datetime.date.today)),
                ('rehearsalEndDate', models.DateField(default=datetime.date.today)),
                ('performanceStartDate', models.DateField(default=datetime.date.today)),
                ('performanceEndDate', models.DateField(default=datetime.date.today)),
                ('visa_requirement', models.TextField(default='')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCallbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFavoriteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='able_in',
            new_name='able_date',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='able_out',
        ),
        migrations.AddField(
            model_name='talent',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='lang1',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'English'), (2, 'Spanish'), (3, 'Portuguese'), (4, 'German'), (5, 'French'), (6, 'Italian'), (7, 'Japanese'), (8, 'Mandarin'), (9, 'Cantonese')], default=0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='lang2',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'English'), (2, 'Spanish'), (3, 'Portuguese'), (4, 'German'), (5, 'French'), (6, 'Italian'), (7, 'Japanese'), (8, 'Mandarin'), (9, 'Cantonese')], default=0),
        ),
        migrations.AlterField(
            model_name='talent',
            name='lang3',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'English'), (2, 'Spanish'), (3, 'Portuguese'), (4, 'German'), (5, 'French'), (6, 'Italian'), (7, 'Japanese'), (8, 'Mandarin'), (9, 'Cantonese')], default=0),
        ),
        migrations.AddField(
            model_name='clientfavoritemodel',
            name='talent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Talent'),
        ),
        migrations.AddField(
            model_name='clientcallbackmodel',
            name='talent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Talent'),
        ),
    ]
