# Generated by Django 2.0.5 on 2019-01-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('talent', '0002_talent_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_requests', to='client.Client')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_client_requests', to='talent.Talent')),
            ],
            options={
                'db_table': 'client_request',
                'ordering': ('id', 'client', 'talent', 'created'),
                'managed': True,
            },
        ),
    ]
