# Generated by Django 2.0.2 on 2018-07-23 00:13

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', s3direct.fields.S3DirectField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_videos', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_video',
                'ordering': ('talent', 'created', 'file'),
                'managed': True,
            },
        ),
    ]
