# Generated by Django 2.0.2 on 2018-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_video', '0003_auto_20180723_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentvideo',
            options={'managed': True, 'ordering': ('talent', 'updated', 'name')},
        ),
        migrations.RenameField(
            model_name='talentvideo',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='talentvideo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='talentvideo',
            name='file',
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='file_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
