# Generated by Django 2.0.2 on 2018-08-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_video', '0004_auto_20180724_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentvideo',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
