# Generated by Django 2.0.2 on 2018-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_video', '0005_talentvideo_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentvideo',
            name='position_sub_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='position_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
