# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('multi_selection', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('related_position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_skills', to='position_type.PositionType')),
            ],
            options={
                'db_table': 'skill',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'id')},
        ),
    ]
