# Generated by Django 2.0.5 on 2018-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_skill_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='question',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
