# Generated by Django 2.0.2 on 2018-10-01 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, default=datetime.date.today)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_visas', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_visa',
                'ordering': ('talent', 'name', 'expiration_date'),
                'managed': True,
            },
        ),
    ]
