# Generated by Django 2.0.5 on 2018-11-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        ('sub_skill', '0002_auto_20181121_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentVideoSubSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sub_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sub_skills', to='sub_skill.SubSkill')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_video_sub_skills', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_video_sub_skill',
                'ordering': ('talent', 'sub_skill', 'updated'),
                'managed': True,
            },
        ),
    ]
