# Generated by Django 2.0.5 on 2018-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_video_sub_skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentvideosubskill',
            options={'managed': True, 'ordering': ('talent', 'sub_skill', 'priority', 'updated')},
        ),
        migrations.AddField(
            model_name='talentvideosubskill',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
