# Generated by Django 2.0.5 on 2018-11-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_video_sub_skill', '0002_auto_20181121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentvideosubskill',
            name='priority',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
