# Generated by Django 2.0.5 on 2019-01-01 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_teams', to='client.Client')),
            ],
            options={
                'db_table': 'team',
                'ordering': ('id', 'client', 'created'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('client',)},
        ),
    ]
