# Generated by Django 2.0.5 on 2018-12-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='viewed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
