# Generated by Django 2.0.5 on 2019-01-01 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_member', '0001_initial'),
        ('talent', '0002_talent_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_shared_profiles', to='talent.Talent')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_shared_profiles', to='team_member.TeamMember')),
            ],
            options={
                'db_table': 'shared_profile',
                'ordering': ('id', 'team_member', 'talent', 'created'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sharedprofile',
            unique_together={('team_member', 'talent')},
        ),
    ]
