# Generated by Django 2.0.5 on 2019-01-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedprofile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
