# Generated by Django 2.0.2 on 2018-07-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent_position_sub_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('talent_position_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='talent_position_sub_type.TalentPositionSubType')),
            ],
            options={
                'db_table': 'question',
                'ordering': ('content',),
                'managed': True,
            },
        ),
    ]
