# Generated by Django 2.0.2 on 2018-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_sub_type', models.CharField(blank=True, max_length=120, null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='position_type.PositionType')),
            ],
            options={
                'db_table': 'question',
                'ordering': ('content',),
                'managed': True,
            },
        ),
    ]
