# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'ordering': ('id',)},
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
