# Generated by Django 2.0.2 on 2018-07-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='talent_position_sub_type',
            new_name='talent_position_type',
        ),
    ]
