# Generated by Django 2.0.2 on 2018-07-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'ordering': ('content',)},
        ),
    ]
