# Generated by Django 2.0.2 on 2018-07-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180726_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='talent_position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='talent_position_type.TalentPositionType'),
        ),
    ]
