# Generated by Django 2.0.2 on 2018-07-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180726_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='talent_position_sub_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
