# Generated by Django 2.0.5 on 2018-12-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedprofile',
            name='description',
            field=models.CharField(choices=[('hour', 'Block for an hour'), ('today', 'Block for today'), ('week', 'Block for a week'), ('month', 'Block for a month'), ('six months', 'Block for six months'), ('forever', 'Block forever')], default='month', max_length=50),
        ),
    ]
