# Generated by Django 2.0.5 on 2018-11-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_video_greeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentvideogreeting',
            options={'managed': True, 'ordering': ('talent', 'priority', 'updated')},
        ),
        migrations.AddField(
            model_name='talentvideogreeting',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
