# Generated by Django 2.0.5 on 2019-02-13 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('note_type', models.CharField(choices=[('Profile', 'Profile'), ('CastingRequest', 'CastingRequest'), ('Search', 'Search'), ('View', 'View'), ('Favorite', 'Favorite'), ('Share', 'Share'), ('Block', 'Block'), ('MedicalCondition', 'MedicalCondition'), ('Medical', 'Medical'), ('Login', 'Login'), ('TID', 'TID'), ('ChangePassword', 'ChangePassword'), ('Rating', 'Rating'), ('PersonalInfo', 'PersonalInfo'), ('Immigration', 'Immigration'), ('Language', 'Language')], default='Profile', max_length=30)),
                ('note', models.TextField(default='', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actor_notes', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_note',
                'ordering': ('created',),
                'managed': True,
            },
        ),
    ]
