# Generated by Django 2.0.5 on 2019-02-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0002_auto_20190213_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernote',
            options={'managed': True, 'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='usernote',
            name='object_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usernote',
            name='object_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
