# Generated by Django 2.0.5 on 2019-02-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0004_auto_20190215_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='note_type',
            field=models.CharField(choices=[('Profile', 'Profile'), ('CastingRequest', 'CastingRequest'), ('CastingRequestTalent', 'CastingRequestTalent'), ('DanceCombination', 'DanceCombination'), ('Search', 'Search'), ('View', 'View'), ('Favorite', 'Favorite'), ('Share', 'Share'), ('Block', 'Block'), ('MedicalCondition', 'MedicalCondition'), ('Medical', 'Medical'), ('Login', 'Login'), ('Logout', 'Logout'), ('TID', 'TID'), ('ChangePassword', 'ChangePassword'), ('Rating', 'Rating'), ('PersonalInfo', 'PersonalInfo'), ('Immigration', 'Immigration'), ('Language', 'Language')], default='Profile', max_length=30),
        ),
    ]
