# Generated by Django 2.0.5 on 2018-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WizardQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question', models.TextField(blank=True, max_length=300)),
                ('multi_selection', models.BooleanField(default=False)),
                ('selection_title', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'wizard_question',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='wizardquestion',
            unique_together={('name', 'id')},
        ),
    ]
