# Generated by Django 2.0.5 on 2018-12-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        ('casting_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingRequestTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal_wage', models.IntegerField(blank=True, default=0)),
                ('performance_wage', models.IntegerField(blank=True, default=0)),
                ('comment', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('casting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_request_talents', to='casting_request.CastingRequest')),
                ('talents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_casting_requests', to='talent.Talent')),
            ],
            options={
                'db_table': 'casting_request_talents',
                'ordering': ('id', 'casting_request', 'created'),
                'managed': True,
            },
        ),
    ]
