# Generated by Django 2.0.5 on 2018-12-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_request_talent', '0002_auto_20181219_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingrequesttalent',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
