# Generated by Django 2.0.5 on 2018-12-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting_request_talent', '0003_auto_20181219_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castingrequesttalent',
            old_name='talents',
            new_name='talent',
        ),
    ]
