# Generated by Django 2.0.5 on 2018-12-21 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_talent_tid'),
        ('casting_request', '0002_castingrequest_status_updated_date'),
        ('casting_request_talent', '0004_auto_20181220_0002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='castingrequesttalent',
            unique_together={('casting_request', 'talent')},
        ),
    ]
